<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://apache.org" 
         xmlns:xsi="http://w3.org" 
         xsi:schemaLocation="http://apache.org https://apache.org">
    <modelVersion>4.0.0</modelVersion>
    
    <groupId>6029</groupId>
    <artifactId>6029</artifactId>
    <version>1.0.0</version>
    <packaging>war</packaging>

    <dependencies>
    <!-- Librería para Encriptar Contraseñas -->
    <dependency>
        <groupId>org.mindrot</groupId>
        <artifactId>jbcrypt</artifactId>
        <version>0.4</version>
    </dependency>
    
    <!-- Librerías para Logs de Auditoría -->
    <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-api</artifactId>
        <version>2.0.13</version>
    </dependency>
    <dependency>
        <groupId>ch.qos.logback</groupId>
        <artifactId>logback-classic</artifactId>
        <version>1.5.6</version>
    </dependency>
    </dependencies>

    <properties>
        <maven.compiler.source>26</maven.compiler.source>
        <maven.compiler.target>26</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

</project>